routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\Stock;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/stocks', 'StockController');

Route::resource('/products', 'ProductController');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-items-center mb-3">
                            <strong>Stocks</strong>
{{--                            <div class="input-group-text ml-2 mr-4">--}}
{{--                                <input type="checkbox" value="true" id="defaultCheck" checked>--}}
{{--                            </div>--}}
                            <date-picker id="date-time" class=" ml-auto"></date-picker>
                            <a href="" id="btn-filter" type="button" class="btn btn-primary px-3 mx-3">Go</a>
                            <a href="/products/create" type="button" class="btn btn-primary {{ $disbl }}" >ADD</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table table-bordered" id="stocks-table">
                            <thead>
                            <tr>
                                <th>Date</th>
                                <th>Stock</th>
                                <th>Client Name</th>
                                <th>Buy/Sell</th>
                                <th>Quantity</th>
                                <th>Price</th>
                                <th>Percentage Traded %</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $(function() {
            let dt = $('#stocks-table').DataTable({
                processing: true,
                serverSide: true,
                lengthMenu: [[100, 200, 400, 600, 800, 1000], [100, 200, 400, 600, 800, 1000]],
                pageLength: 600,
                ajax: {
                    'url': '{!! route('products.index') !!}',
                    'data': function ( d ) {
                        d.start_date = $('#start-date').val()
                        d.end_date = $('#end-date').val()
                        d.filter = $('#defaultCheck').val()
                    }
                },
                columns: [
                    { data: 'date', name: 'date' },
                    { data: 'stock', name: 'stock' },
                    { data: 'client_name', name: 'client_name' },
                    { data: 'action', name: 'action' },
                    { data: 'quantity', name: 'quantity' },
                    { data: 'price', name: 'price' },
                    { data: 'pre_traded', name: 'pre_traded' },
                ]
            });

            $('#btn-filter').click(function(e){
                e.preventDefault();
                dt.draw()
            });

            $('#defaultCheck').click(function (e) {
                $('#defaultCheck').attr('checked', this.checked);
                $('#defaultCheck').attr('value', this.checked);
                // e.preventDefault();
                dt.draw()
            })
        });
    </script>
@endpush

resources/views/stock.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-items-center mb-3">
                            <strong>Stocks</strong>
                            <div class="input-group-text ml-2 mr-4">
                                <input type="checkbox" value="true" id="defaultCheck" checked>
                            </div>
                            <date-picker id="date-time" class=" ml-auto"></date-picker>
                            <a href="" id="btn-filter" type="button" class="btn btn-primary px-3 mx-3">Go</a>
                            <a href="/stocks/create" type="button" class="btn btn-primary {{ $disbl }}" >ADD</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table table-bordered" id="stocks-table">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Close</th>
                                <th>SMA 5</th>
                                <th>SMA 10</th>
                                <th>SMA 15</th>
                                <th>SMA 20</th>
                                <th>SMA 50</th>
                                <th>SMA 100</th>
                                <th>SMA 200</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $(function() {
            let dt = $('#stocks-table').DataTable({
                processing: true,
                serverSide: true,
                lengthMenu: [[100, 200, 400, 600, 800, 1000], [100, 200, 400, 600, 800, 1000]],
                pageLength: 600,
                ajax: {
                    'url': '{!! route('stocks.index') !!}',
                    'data': function ( d ) {
                        d.start_date = $('#start-date').val()
                        d.end_date = $('#end-date').val()
                        d.filter = $('#defaultCheck').val()
                    }
                },
                columns: [
                    { data: 'name', name: 'name' },
                    { data: 'close', name: 'close' },
                    { data: 'sma5', name: 'sma5' },
                    { data: 'sma10', name: 'sma10' },
                    { data: 'sma15', name: 'sma15' },
                    { data: 'sma20', name: 'sma20' },
                    { data: 'sma50', name: 'sma50' },
                    { data: 'sma100', name: 'sma100' },
                    { data: 'sma200', name: 'sma200' },
                ]
            });

            $('#btn-filter').click(function(e){
                e.preventDefault();
                dt.draw()
            });

            $('#defaultCheck').click(function (e) {
                $('#defaultCheck').attr('checked', this.checked);
                $('#defaultCheck').attr('value', this.checked);
                // e.preventDefault();
                dt.draw()
            })
        });
    </script>
@endpush